apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cve-parser
  namespace: cves
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cve-parser
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
          - image: phiroict/rh_cve_parser_aro:20230208.0
            name: cve-parser
            resources: {}
            securityContext:
              capabilities:
                drop:
                  - 'ALL'
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
