apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cve-parser
  namespace: cves
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cve-parser
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: phiroict/rh_cve_parser_aro:20230212.2
            name: cve-parser
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            volumeMounts:
            - mountPath: /src/result
              name: results
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
          volumes:
          - emptyDir:
              sizeLimit: 20Mi
            name: results
  schedule: '*/1 * * * *'
status: {}
