apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "cves-resource-limits" 
  namespace: cves
spec:
  limits: 
    - type: "Container"
      max:
        cpu: "1" 
        memory: "1Gi" 
      min:
        cpu: "10m" 
        memory: "4Mi" 
      default:
        cpu: "100m" 
        memory: "100Mi" 
      defaultRequest:
        cpu: "50m" 
        memory: "50Mi" 
      maxLimitRequestRatio:
        cpu: "10"